version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
  
  jenkins:
    build: ./
    container_name: ci_jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - frontend

volumes:
  jenkins_home: