services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=libros
      - DB_USER=root
      - DB_PASSWORD=rootpassword

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8081:80"
    volumes:
      - ./data:/usr/share/nginx/html/data
    depends_on:
      - backend
  
  jenkins:
    build: ./
    container_name: ci_jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - frontend
  db:
    image: mysql:8.0
    container_name: mysql_libros
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: libros
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  jenkins_home:
  mysql_data:
